### ISSUE TITLE
Don't use Allterco in manufacturer field

### ISSUE THREAD

**Issue by kzyapkov** [ioprev/shelly-firmware#1]
Hi,

Writing on behalf of Allterco, that's an interesting piece of code you've created! We only request that you change the value stored in the `manufacturer` field of the added hwinfo -- don't mention Allterco, but put a reference to your script instead. `hw_revision` could also be something else, like "recovered shelly device".

**Comment by ioprev** [comment]
Hi @kzyapkov 

Thanks for your message! I really appreciate your feedback.
What I use now is exactly what I got from a Shelly device flash, so I didn't got time to play with these fields (and check if different values will work)

Will post these changes in a couple of days; need to verify on at least one device first.

Thank you,
John

**Comment by kzyapkov** [comment]
These fields don't affect the functionality of the firmware in any way. On some models there are device-specific fields which are used, like display model or values of shunt resistors and such, which do affect the functionality and need to be set correctly. Also, CC3200-based devices won't work with this script -- hwinfo is not stored on the SPIFFS partition.

**Comment by ioprev** [comment]
Okay, thanks @kzyapkov 

Further testing will be needed for more devices. Closing for now
