### ISSUE TITLE
cannot stat 'fs-tools/tools/mkspiffs8': No such file or directory

### ISSUE THREAD

**Issue by FraatGIT** [ioprev/shelly-firmware#6]
I will get when run  ./build_tools.sh

cp: cannot stat 'fs-tools/tools/mkspiffs8': No such file or directory
cp: cannot stat 'fs-tools/tools/unspiffs8': No such file or directory

$ ./build_tools.sh
Cloning into 'fs-tools'...
remote: Enumerating objects: 151, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 151 (delta 13), reused 27 (delta 9), pack-reused 114
Receiving objects: 100% (151/151), 103.71 KiB | 4.15 MiB/s, done.
Resolving deltas: 100% (61/61), done.
Cloning into 'frozen'...
remote: Enumerating objects: 686, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 686 (delta 2), reused 5 (delta 0), pack-reused 675
Receiving objects: 100% (686/686), 322.82 KiB | 7.69 MiB/s, done.
Resolving deltas: 100% (415/415), done.
(Stripping trailing CRs from patch; use --binary to disable.)
patching file tools/Makefile
./build_tools.sh: line 7: make: command not found
cp: cannot stat 'fs-tools/tools/mkspiffs8': No such file or directory
cp: cannot stat 'fs-tools/tools/unspiffs8': No such file or directory

**Comment by ioprev** [comment]
You need `make` tool as well as a C compiler installed in order to build the fs-tools.
